name: Compile LaTeX Document

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install custom fonts
      run: |
        mkdir -p ~/.fonts
        cp fonts/*.ttf ~/.fonts/
        fc-cache -fv

    - name: List available fonts
      run: |
        fc-list : file family style

    - name: Compiling PDF using lualatex
      uses: xu-cheng/latex-action@v2
      continue-on-error: true  # Allow the workflow to continue even if this step fails
      with:
        root_file: oficio-parvo.tex
        latexmk_shell_escape: yes
        latexmk_use_lualatex: yes

    - name: Upload PDF (if compilation is successful)
      uses: actions/upload-artifact@v2
      if: success()
      with:
        name: Compiled-PDF
        path: ./oficio-parvo.pdf

    - name: Upload LaTeX Log File
      uses: actions/upload-artifact@v2
      if: always()  # This ensures the log is uploaded regardless of the previous step's success or failure
      with:
        name: LaTeX-Log
        path: ./oficio-parvo.log

